import { useEffect, useRef, useState } from 'react'

type View = 'home'|'operation'|'records'|'settings'
type Operator = { id:number; name:string; role:string }
type Attendance = { child_id:number; name:string; boarded_at:string|null; alighted_at:string|null }
type TripStatus = { trip_id:number; status:string; boarded:number; alighted:number; unconfirmed:number; children:Attendance[] }
type Dashboard = { organization_name:string; date:string; today_trip_count:number; active_trip_count:number; completed_trip_count:number; unconfirmed_count:number; recent_trips:Array<{trip_id:number;status:string;direction:string;started_at:string;unconfirmed:number}> }
type Mode = '乗車'|'降車'
type OfflineEvent = { client_event_id:string; trip_id:number; qr_token:string; event_type:Mode }
const CONFIGURED_API = (import.meta.env.VITE_API_BASE_URL || '').trim()
const API = CONFIGURED_API || 'http://127.0.0.1:8000'
const OFFLINE_KEY = 'mamoru-bus-offline-events'
const demoChildren: Attendance[] = [{child_id:1,name:'さくら ちゃん',boarded_at:null,alighted_at:null},{child_id:2,name:'はると くん',boarded_at:null,alighted_at:null}]
const demoDashboard: Dashboard = {organization_name:'デモ幼稚園',date:new Date().toISOString().slice(0,10),today_trip_count:1,active_trip_count:0,completed_trip_count:0,unconfirmed_count:0,recent_trips:[]}
const queue = (): OfflineEvent[] => JSON.parse(localStorage.getItem(OFFLINE_KEY) || '[]')
const saveQueue = (items: OfflineEvent[]) => localStorage.setItem(OFFLINE_KEY, JSON.stringify(items))

export default function App(){
 const [view,setView]=useState<View>('home'),[operator,setOperator]=useState<Operator|null>(null),[token,setToken]=useState<string|null>(localStorage.getItem('mamoru-bus-token'))
 const [trip,setTrip]=useState<TripStatus|null>(null),[dashboard,setDashboard]=useState<Dashboard|null>(null),[demo,setDemo]=useState(false)
 const [mode,setMode]=useState<Mode>('乗車'),[scanner,setScanner]=useState(false),[tailScanner,setTailScanner]=useState(false),[tailDone,setTailDone]=useState(false),[approved,setApproved]=useState(false)
 const [message,setMessage]=useState('ログインして本日の状況を確認してください'),[offlineCount,setOfflineCount]=useState(queue().length)
 const auth=(init:RequestInit={})=>({...init,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`,...(init.headers||{})}})
 const logout=()=>{localStorage.removeItem('mamoru-bus-token');setToken(null);setOperator(null);setTrip(null);setDashboard(null);setDemo(false);setView('home');setMessage('ログアウトしました')}
 const loadDashboard=async()=>{if(token==='demo'){setDashboard(demoDashboard);return} if(!token)return; try{const r=await fetch(API+'/api/dashboard',auth());if(!r.ok)throw new Error();setDashboard(await r.json())}catch{setMessage('本日の集計を取得できませんでした')}}
 const sync=async()=>{if(!token||token==='demo'||!queue().length)return;try{const r=await fetch(API+'/api/sync',auth({method:'POST',body:JSON.stringify({events:queue()})}));if(!r.ok)return;saveQueue([]);setOfflineCount(0);setMessage('オフライン記録を同期しました');await loadDashboard()}catch{}}
 useEffect(()=>{if(token==='demo'){logout();return}if(token)fetch(API+'/api/auth/me',auth()).then(r=>r.ok?r.json():Promise.reject()).then(x=>{setOperator(x);loadDashboard();sync()}).catch(logout)},[token])
 useEffect(()=>{const online=()=>sync();window.addEventListener('online',online);return()=>window.removeEventListener('online',online)},[token])
 const login=(staff:Operator,accessToken:string)=>{localStorage.setItem('mamoru-bus-token',accessToken);setToken(accessToken);setOperator(staff);setMessage(accessToken==='demo'?'デモモードです。記録は保存されません':'ログインしました')}
 const startTrip=async()=>{if(!token)return;try{const r=await fetch(API+'/api/trips',auth({method:'POST',body:JSON.stringify({direction:'帰り'})}));if(!r.ok)throw new Error();const x=await r.json();setTrip({trip_id:x.id,status:'運行中',boarded:0,alighted:0,unconfirmed:0,children:[]});setView('operation');setMessage(`帰り便 #${x.id} を開始しました`);await loadDashboard()}catch{setMessage('便を開始できません。API接続を確認してください。')}}
 const refresh=async(id:number)=>{const r=await fetch(`${API}/api/trips/${id}/status`,auth());if(!r.ok)throw new Error();setTrip(await r.json());await loadDashboard()}
 const resumeActiveTrip=async()=>{try{const r=await fetch(`${API}/api/trips?status_filter=運行中`,auth());if(!r.ok)throw new Error();const trips=await r.json();if(!trips[0]){setMessage('進行中の便はありません');setView('operation');return}await refresh(trips[0].trip_id);setView('operation');setMessage('進行中の便を再開しました')}catch{setMessage('進行中の便を取得できません。API接続を確認してください。')}}
 const scan=async(qr:string)=>{if(!trip)return;if(demo){const child=demoChildren.find((_,i)=>qr===`child-${i+1}`)||demoChildren[0];const children=(trip.children.length?trip.children:demoChildren).map(x=>x.child_id===child.child_id?{...x,boarded_at:mode==='乗車'?new Date().toISOString():x.boarded_at,alighted_at:mode==='降車'?new Date().toISOString():x.alighted_at}:x);const boarded=children.filter(x=>x.boarded_at).length,alighted=children.filter(x=>x.alighted_at).length;setTrip({...trip,children,boarded,alighted,unconfirmed:boarded-alighted});setScanner(false);return}try{const r=await fetch(`${API}/api/trips/${trip.trip_id}/scans`,auth({method:'POST',body:JSON.stringify({qr_token:qr,event_type:mode})}));if(!r.ok)throw new Error();await refresh(trip.trip_id);setScanner(false)}catch{const items=[...queue(),{client_event_id:crypto.randomUUID(),trip_id:trip.trip_id,qr_token:qr,event_type:mode}];saveQueue(items);setOfflineCount(items.length);setScanner(false);setMessage('通信できないため端末内に保留しました')}}
 const tail=async(qr:string)=>{if(!trip||qr!=='bus-tail-2'){setMessage('最後尾QRではありません');return}try{let latitude:string|undefined,longitude:string|undefined;if(navigator.geolocation){const p=await new Promise<GeolocationPosition>((ok,ng)=>navigator.geolocation.getCurrentPosition(ok,ng,{timeout:5000}));latitude=String(p.coords.latitude);longitude=String(p.coords.longitude)}if(!demo){const r=await fetch(API+'/api/vehicle-checks',auth({method:'POST',body:JSON.stringify({trip_id:trip.trip_id,check_type:'tail_qr',qr_token:qr,latitude,longitude})}));if(!r.ok)throw new Error()}setTailDone(true);setTailScanner(false);setMessage('最後尾確認を記録しました')}catch{setMessage('最後尾確認を保存できませんでした')}}
 const approve=async(staffId:number,pin:string)=>{if(!trip)return;try{if(!demo){const r=await fetch(`${API}/api/trips/${trip.trip_id}/third-party-approval`,auth({method:'POST',body:JSON.stringify({staff_id:staffId,pin})}));if(!r.ok)throw new Error()}setApproved(true);setMessage('第三者確認を記録しました')}catch{setMessage('第三者確認者のID・PINまたは権限を確認してください')}}
 const complete=async()=>{if(!trip||trip.unconfirmed||!tailDone||!approved)return;try{if(!demo){const r=await fetch(`${API}/api/trips/${trip.trip_id}/complete`,auth({method:'POST'}));if(!r.ok)throw new Error()}setTrip({...trip,status:'完了'});setMessage('便の安全確認が完了しました');await loadDashboard()}catch{setMessage('便を完了できません。確認項目を見直してください')}}
 const content=!operator?<Login onLogin={login}/>:view==='home'?<Home dashboard={dashboard} demo={demo} onStart={startTrip} onOperation={resumeActiveTrip}/>:view==='operation'?<Operation trip={trip} mode={mode} setMode={setMode} onStart={resumeActiveTrip} onScan={()=>setScanner(true)} onTail={()=>setTailScanner(true)} tailDone={tailDone} approved={approved} onApprove={approve} onComplete={complete}/>:<ComingSoon view={view}/>
 return <div className="app"><header className="px-5 pt-5 pb-4 bg-white flex justify-between"><div><div className="text-xs font-bold text-teal">送迎バス安全確認</div><b className="text-xl">まもるバス</b></div><button className="border-0 bg-white text-sm font-bold" onClick={operator?logout:undefined}>{operator?.name??'ログイン'}</button></header><main className="px-5 pb-24">{offlineCount>0&&<button className="w-full rounded-xl bg-amber-100 p-3 text-sm font-bold text-amber-900" onClick={sync}>⏳ 未同期の記録 {offlineCount} 件 — 同期する</button>}<section className="mt-3 rounded-2xl bg-sand p-4 border border-amber-100"><p className="m-0 text-sm">{message}</p></section>{content}</main>{operator&&<Nav active={view} onChange={setView}/>} {scanner&&<Scanner title={`${mode}QRを読み取る`} onRead={scan} onClose={()=>setScanner(false)}/>} {tailScanner&&<Scanner title="最後尾QRを読み取る" onRead={tail} onClose={()=>setTailScanner(false)}/>}</div>
}
function Home({dashboard,demo,onStart,onOperation}:{dashboard:Dashboard|null;demo:boolean;onStart:()=>void;onOperation:()=>void}){const data=dashboard||demoDashboard;return <><section className="mt-4 rounded-3xl bg-teal p-5 text-white"><p className="m-0 text-sm opacity-85">{data.organization_name}</p><h1 className="mt-1 mb-2 text-2xl font-black">本日の送迎状況</h1><p className="m-0 text-sm">{data.date} {demo&&'・デモ表示'}</p></section><section className="grid grid-cols-3 gap-3 mt-4"><Metric label="本日の便" value={data.today_trip_count}/><Metric label="運行中" value={data.active_trip_count}/><Metric label="未確認" value={data.unconfirmed_count} danger={data.unconfirmed_count>0}/></section><section className="card mt-4 p-5"><h2 className="m-0 text-lg font-black">運行を開始</h2><p className="text-sm text-slate-600">帰り便を開始し、園児の乗車・降車確認へ進みます。</p><button className="big-action" onClick={onStart}>帰り便を開始する</button><button className="mt-3 w-full rounded-xl border border-teal bg-white p-3 font-bold text-teal" onClick={onOperation}>進行中の便を確認する</button></section><section className="card mt-4 p-5"><h2 className="m-0 text-lg font-black">安全確認</h2><p className="mb-0 text-sm text-slate-600">未確認がある便は、最後尾確認と完了処理を行えません。画面の表示だけで安全と判断せず、必ず車内を目視確認してください。</p></section></>}
function Metric({label,value,danger}:{label:string;value:number;danger?:boolean}){return <section className="card p-3 text-center"><b className={'text-2xl '+(danger?'text-coral':'text-teal')}>{value}</b><br/><span className="text-xs">{label}</span></section>}
function Operation({trip,mode,setMode,onStart,onScan,onTail,tailDone,approved,onApprove,onComplete}:{trip:TripStatus|null;mode:Mode;setMode:(v:Mode)=>void;onStart:()=>void;onScan:()=>void;onTail:()=>void;tailDone:boolean;approved:boolean;onApprove:(id:number,pin:string)=>void;onComplete:()=>void}){if(!trip)return <section className="card mt-4 p-5"><h1 className="m-0 text-xl font-black">運行</h1><p className="text-sm">進行中の便はありません。</p><button className="big-action" onClick={onStart}>帰り便を開始する</button></section>;const safety=trip.boarded>0&&trip.unconfirmed===0;return <><section className="card mt-4 p-4"><h1 className="m-0 text-xl font-black">帰り便 #{trip.trip_id||'デモ'}</h1><div className="grid grid-cols-3 text-center mt-3"><Metric label="乗車" value={trip.boarded}/><Metric label="降車" value={trip.alighted}/><Metric label="未降車" value={trip.unconfirmed} danger={trip.unconfirmed>0}/></div></section><div className="grid grid-cols-2 gap-3 mt-4"><button className={'rounded-2xl p-4 font-bold border-2 '+(mode==='乗車'?'bg-sky-600 text-white border-sky-600':'bg-white border-slate-200')} onClick={()=>setMode('乗車')}>乗車を記録</button><button className={'rounded-2xl p-4 font-bold border-2 '+(mode==='降車'?'bg-teal text-white border-teal':'bg-white border-slate-200')} onClick={()=>setMode('降車')}>降車を記録</button></div><button className="big-action mt-4" onClick={onScan}>📷 {mode}QRを読み取る</button><section className="card mt-4 overflow-hidden"><h2 className="p-4 m-0 text-lg font-black">この便の園児</h2>{trip.children.map(x=><div className="px-4 py-3 border-t flex justify-between" key={x.child_id}><span>{x.name}</span><span className="badge bg-slate-100">{!x.boarded_at?'未乗車':x.alighted_at?'降車済':'未降車'}</span></div>)}</section><section className={'card mt-4 p-4 '+(!safety?'opacity-50':'')}><h2 className="m-0 text-lg font-black">車内安全確認</h2><button disabled={!safety||tailDone} className="big-action mt-3 disabled:opacity-40" onClick={onTail}>最後尾QRを確認する</button>{tailDone&&<ThirdApproval onApprove={onApprove}/>}<button disabled={!safety||!tailDone||!approved} className="mt-3 w-full rounded-xl bg-slate-800 p-4 font-bold text-white disabled:opacity-40" onClick={onComplete}>便を完了する</button></section></>}
function ComingSoon({view}:{view:View}){const title=view==='records'?'記録':'設定';return <section className="card mt-4 p-5"><h1 className="m-0 text-xl font-black">{title}</h1><p className="text-sm text-slate-600">この画面は次の段階で、実記録・監査ログまたは園情報・園児・職員・車両・通知先の管理画面として接続します。</p></section>}
function Nav({active,onChange}:{active:View;onChange:(v:View)=>void}){return <nav className="nav"><button className={active==='home'?'active':''} onClick={()=>onChange('home')}>⌂<span>ホーム</span></button><button className={active==='operation'?'active':''} onClick={()=>onChange('operation')}>🚌<span>運行</span></button><button className={active==='records'?'active':''} onClick={()=>onChange('records')}>▤<span>記録</span></button><button className={active==='settings'?'active':''} onClick={()=>onChange('settings')}>⚙<span>設定</span></button></nav>}
function Login({onLogin}:{onLogin:(x:Operator,t:string)=>void}){const [id,setId]=useState(''),[pin,setPin]=useState(''),[error,setError]=useState('');const submit=async()=>{let legacy=false;try{const r=await fetch(API+'/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({staff_id:Number(id),pin})});if(!r.ok)throw new Error();const d=await r.json();if(!d.access_token||!d.staff){legacy=true;throw new Error()}onLogin(d.staff,d.access_token)}catch{setError('本番APIへログインできません。職員ID・PINとAPI接続を確認してください。')}};return <section className="card mt-4 p-5"><h1 className="m-0 text-xl font-black">職員ログイン</h1><p className="text-sm">本番APIの職員IDとPINを入力してください。</p><input className="w-full border rounded-xl p-3 mb-2" inputMode="numeric" value={id} onChange={e=>setId(e.target.value)} placeholder="職員ID"/><input className="w-full border rounded-xl p-3" type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="PIN"/><button className="big-action mt-3" onClick={submit}>ログイン</button>{error&&<p className="text-sm text-red-700">{error}</p>}</section>}
function ThirdApproval({onApprove}:{onApprove:(id:number,pin:string)=>void}){const [id,setId]=useState(''),[pin,setPin]=useState('');return <div className="mt-3"><input className="w-full border rounded-xl p-3 mb-2" value={id} onChange={e=>setId(e.target.value)} placeholder="第三者確認者の職員ID"/><input className="w-full border rounded-xl p-3" type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="第三者確認者のPIN"/><button className="mt-2 w-full rounded-xl bg-teal p-3 font-bold text-white" onClick={()=>id&&pin&&onApprove(Number(id),pin)}>第三者承認する</button></div>}
type Detector={detect:(s:ImageBitmapSource)=>Promise<Array<{rawValue:string}>>};declare global{interface Window{BarcodeDetector?:new(o:{formats:string[]})=>Detector}}
function Scanner({title,onRead,onClose}:{title:string;onRead:(v:string)=>void;onClose:()=>void}){const video=useRef<HTMLVideoElement>(null),[manual,setManual]=useState('');useEffect(()=>{let stream:MediaStream|undefined;let timer=0;(async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});if(video.current)video.current.srcObject=stream;if(window.BarcodeDetector){const d=new window.BarcodeDetector({formats:['qr_code']});timer=window.setInterval(async()=>{if(video.current){const found=await d.detect(video.current);if(found[0])onRead(found[0].rawValue)}},700)}}catch{}})();return()=>{clearInterval(timer);stream?.getTracks().forEach(t=>t.stop())}},[onRead]);return <div className="modal"><div className="sheet"><h2 className="text-center text-xl font-black">{title}</h2><video ref={video} autoPlay playsInline muted className="w-full aspect-square bg-slate-900 rounded-2xl"/><div className="flex gap-2 mt-3"><input className="flex-1 border rounded-xl p-3" value={manual} onChange={e=>setManual(e.target.value)} placeholder="QR文字列"/><button className="bg-teal text-white rounded-xl px-3" onClick={()=>manual&&onRead(manual)}>送信</button></div><button className="w-full p-3 border-0 bg-white" onClick={onClose}>キャンセル</button></div></div>}