import { useEffect, useRef, useState } from 'react'

type Operator = { id:number; name:string; role:string }
type Attendance = { child_id:number; name:string; boarded_at:string|null; alighted_at:string|null }
type TripStatus = { trip_id:number; status:string; boarded:number; alighted:number; unconfirmed:number; children:Attendance[] }
type Mode = '乗車'|'降車'
const API = import.meta.env.VITE_API_BASE_URL || 'http://127.0.0.1:8000'
const demoChildren: Attendance[] = [
  {child_id:1,name:'さくら ちゃん',boarded_at:null,alighted_at:null},
  {child_id:2,name:'はると くん',boarded_at:null,alighted_at:null},
  {child_id:3,name:'みお ちゃん',boarded_at:null,alighted_at:null},
  {child_id:4,name:'りく くん',boarded_at:null,alighted_at:null},
]

export default function App(){
 const [operator,setOperator]=useState<Operator|null>(null)
 const [trip,setTrip]=useState<TripStatus|null>(null)
 const [mode,setMode]=useState<Mode>('乗車')
 const [scanner,setScanner]=useState(false)
 const [message,setMessage]=useState('便を開始してください')
 const [demo,setDemo]=useState(false)
 const [tailDone,setTailDone]=useState(false)
 const [approved,setApproved]=useState(false)
 const [tailScan,setTailScan]=useState(false)
 const startTrip=async()=>{try{const r=await fetch(API+'/api/trips',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({direction:'帰り'})});if(!r.ok)throw new Error();const data=await r.json();setTrip({trip_id:data.id,status:'運行中',boarded:0,alighted:0,unconfirmed:0,children:[]});setMessage(`帰り便 #${data.id} を開始しました`);setDemo(false)}catch{setTrip({trip_id:0,status:'運行中',boarded:0,alighted:0,unconfirmed:0,children:demoChildren});setMessage('デモ便を開始しました（記録は保存されません）');setDemo(true)}}
 const scan=async(qr:string)=>{if(!trip||!operator)return;try{if(demo){const i=Number(qr.replace('child-',''))||1;const child=demoChildren[(i-1)%demoChildren.length];const current=trip.children.length?trip.children:[...demoChildren];const children=current.map(x=>x.child_id===child.child_id?{...x,boarded_at:mode==='乗車'?new Date().toISOString():x.boarded_at,alighted_at:mode==='降車'?new Date().toISOString():x.alighted_at}:x);const boarded=children.filter(x=>x.boarded_at).length;const alighted=children.filter(x=>x.alighted_at).length;setTrip({...trip,children,boarded,alighted,unconfirmed:boarded-alighted});setScanner(false);return}const r=await fetch(`${API}/api/trips/${trip.trip_id}/scans`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({qr_token:qr,event_type:mode,staff_id:operator.id,staff_name:operator.name})});if(!r.ok)throw new Error(await r.text());const status=await fetch(`${API}/api/trips/${trip.trip_id}/status`).then(x=>x.json());setTrip(status);setScanner(false)}catch{setMessage(mode==='降車'?'降車できません。先に乗車記録があるか確認してください。':'QRコードまたはAPI接続を確認してください。')}}
 const complete=async()=>{if(!trip||trip.unconfirmed>0||!approved)return;try{if(!demo){const r=await fetch(`${API}/api/trips/${trip.trip_id}/complete`,{method:'POST'});if(!r.ok)throw new Error()}setTrip({...trip,status:'完了'});setMessage('便の安全確認が完了しました')}catch{setMessage('便を完了できません。未降車人数を再確認してください。')}}
 const canSafety=!!trip&&trip.unconfirmed===0&&trip.boarded>0
 return <div className="app"><header className="px-5 pt-5 pb-4 bg-white flex justify-between"><div><div className="text-xs font-bold text-teal">送迎バス安全確認</div><b className="text-xl">まもるバス</b></div><button className="border-0 bg-white text-sm font-bold" onClick={()=>setOperator(null)}>{operator?.name??'ログイン'}</button></header><main className="px-5 pb-6">
 <section className="rounded-3xl bg-sand p-5 border border-amber-100"><div className="flex justify-between"><div><p className="m-0 text-sm font-bold text-amber-800">帰り便　🚌 2号車</p><h1 className="m-0 mt-1 text-2xl font-black">{trip?.status??'便未開始'}</h1></div><span className="badge bg-amber-200 text-amber-900">{demo?'デモ':'記録モード'}</span></div><p className="m-0 mt-3 text-sm">{message}</p></section>
 {!trip?<button className="big-action mt-5" onClick={startTrip}>帰り便を開始する</button>:<><section className="card mt-4 p-4"><div className="grid grid-cols-3 text-center"><div><b className="text-xl">{trip.boarded}</b><br/><span className="text-xs">乗車</span></div><div><b className="text-xl">{trip.alighted}</b><br/><span className="text-xs">降車</span></div><div><b className={'text-xl '+(trip.unconfirmed?'text-coral':'text-teal')}>{trip.unconfirmed}</b><br/><span className="text-xs">未降車</span></div></div></section>
 <div className="grid grid-cols-2 gap-3 mt-4"><button className={'rounded-2xl p-4 font-bold border-2 '+(mode==='乗車'?'bg-sky-600 text-white border-sky-600':'bg-white border-slate-200')} onClick={()=>setMode('乗車')}>🚌 乗車を記録</button><button className={'rounded-2xl p-4 font-bold border-2 '+(mode==='降車'?'bg-teal text-white border-teal':'bg-white border-slate-200')} onClick={()=>setMode('降車')}>🚩 降車を記録</button></div><button disabled={trip.status==='完了'} className="big-action mt-4 disabled:opacity-40" onClick={()=>setScanner(true)}>📷　{mode}QRを読み取る</button>
 <section className="card mt-4 overflow-hidden"><h2 className="p-4 m-0 text-lg font-black">この便の園児</h2>{trip.children.map(x=><div className="px-4 py-3 border-t flex justify-between" key={x.child_id}><span>{x.name}</span><span className={'badge '+(!x.boarded_at?'bg-slate-100 text-slate-500':x.alighted_at?'bg-emerald-100 text-emerald-700':'bg-red-100 text-red-700')}>{!x.boarded_at?'未乗車':x.alighted_at?'降車済':'未降車'}</span></div>)}</section>
 {trip.unconfirmed>0&&<section className="mt-4 rounded-2xl bg-red-100 p-4 text-red-800"><b>⚠ 未降車の園児がいます</b><p className="m-1 text-sm">最後尾確認・第三者承認・便完了はできません。園児の所在を確認してください。</p></section>}
 <section className={'card mt-4 p-4 '+(!canSafety?'opacity-45':'')}><h2 className="m-0 text-lg font-black">車内安全確認</h2><p className="text-sm text-slate-500">全員降車後にだけ進めます。</p><button disabled={!canSafety||tailDone} className="big-action disabled:opacity-40" onClick={()=>setTailScan(true)}>最後尾QRを確認する</button>{tailDone&&<ThirdApproval onApprove={()=>setApproved(true)}/>}<button disabled={!canSafety||!tailDone||!approved||trip.status==='完了'} className="mt-3 w-full rounded-xl bg-slate-800 p-4 font-bold text-white disabled:opacity-40" onClick={complete}>便を完了する</button></section></>}
 </main>{!operator&&<Login onLogin={setOperator}/>} {scanner&&<Scanner title={`${mode}QRを読み取る`} onRead={scan} onClose={()=>setScanner(false)}/>} {tailScan&&<Scanner title="最後尾QRを読み取る" onRead={q=>{if(q==='bus-tail-2'){setTailDone(true);setTailScan(false)}else setMessage('最後尾QRではありません')}} onClose={()=>setTailScan(false)}/>}</div>
}
function Login({onLogin}:{onLogin:(x:Operator)=>void}){const [pin,setPin]=useState('');return <div className="modal"><div className="sheet"><h2 className="text-center text-xl font-black">職員ログイン</h2><p className="text-center text-sm">デモ用PIN：1234</p><input className="w-full border rounded-xl p-3" type="password" inputMode="numeric" value={pin} onChange={e=>setPin(e.target.value)} placeholder="PIN"/><button className="big-action mt-3" onClick={()=>pin==='1234'&&onLogin({id:1,name:'田中 先生',role:'運転担当'})}>ログイン</button></div></div>}
function ThirdApproval({onApprove}:{onApprove:()=>void}){const [pin,setPin]=useState('');return <div className="mt-3"><input className="w-full border rounded-xl p-3" value={pin} type="password" inputMode="numeric" onChange={e=>setPin(e.target.value)} placeholder="第三者確認PIN（デモ：5678）"/><button className="mt-2 w-full rounded-xl bg-teal p-3 font-bold text-white" onClick={()=>pin==='5678'&&onApprove()}>第三者承認する</button></div>}
type Detector={detect:(s:ImageBitmapSource)=>Promise<Array<{rawValue:string}>>};declare global{interface Window{BarcodeDetector?:new(o:{formats:string[]})=>Detector}}
function Scanner({title,onRead,onClose}:{title:string;onRead:(v:string)=>void;onClose:()=>void}){const video=useRef<HTMLVideoElement>(null);const [manual,setManual]=useState('');useEffect(()=>{let stream:MediaStream|undefined;let timer=0;(async()=>{try{stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}});if(video.current)video.current.srcObject=stream;if(window.BarcodeDetector){const d=new window.BarcodeDetector({formats:['qr_code']});timer=window.setInterval(async()=>{if(video.current){const x=await d.detect(video.current);if(x[0])onRead(x[0].rawValue)}},700)}}catch{}})();return()=>{clearInterval(timer);stream?.getTracks().forEach(t=>t.stop())}},[onRead]);return <div className="modal"><div className="sheet"><h2 className="text-center text-xl font-black">{title}</h2><video ref={video} autoPlay playsInline muted className="w-full aspect-square bg-slate-900 rounded-2xl"/><div className="flex gap-2 mt-3"><input className="flex-1 border rounded-xl p-3" value={manual} onChange={e=>setManual(e.target.value)} placeholder="QR文字列（デモは child-1〜4）"/><button className="bg-teal text-white rounded-xl px-3" onClick={()=>manual&&onRead(manual)}>送信</button></div><button className="w-full p-3 border-0 bg-white" onClick={onClose}>キャンセル</button></div></div>}
